### Room list with the info to check if is avaiable or not & why
GET http://localhost:3001/api/v1/room HTTP/1.1

###
POST http://localhost:3001/api/v1/user HTTP/1.1

###
GET http://localhost:3001/api/v1/other HTTP/1.1
