### Room list with the info to check if is avaiable or not & why
GET http://localhost:3001/api/v1/room HTTP/1.1


###
GET http://localhost:3000/api/v1/employee HTTP/1.1

###
POST http://localhost:3001/api/v1/employee HTTP/1.1


