'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Rooms', [
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },
      { id_room_type: 1, roof: 1, is_available: true },

      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },
      { id_room_type: 1, roof: 2, is_available: true },

      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },
      { id_room_type: 1, roof: 3, is_available: true },

      { id_room_type: 1, roof: 4, is_available: true },
      { id_room_type: 1, roof: 4, is_available: true },
      { id_room_type: 1, roof: 4, is_available: true },
      { id_room_type: 1, roof: 4, is_available: true },
      { id_room_type: 1, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 2, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
      { id_room_type: 3, roof: 4, is_available: true },
    ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Rooms', null, {});
  }
};
