### vars
@endpoint = http://localhost:3001/api/v1/rooms
# @api = {{baseUrl}}{{port}}/api/{{version}}
# @endpoint = {{api}}/rooms



### show all rooms
GET {{endpoint}} HTTP/1.1

### get client show all
GET {{endpoint}}?page=3 HTTP/1.1

### show all room types
GET {{endpoint}}/types HTTP/1.1

### show details for one room type
GET {{endpoint}}/types/5 HTTP/1.1
