### vars
@endpoint = http://localhost:3001/api/v1/room
# @api = {{baseUrl}}{{port}}/api/{{version}}
# @endpoint = {{api}}/rooms



### get client show all
GET {{endpoint}} HTTP/1.1

### get client show all
GET {{endpoint}}?page=0 HTTP/1.1

### get client show info
GET {{endpoint}}/types HTTP/1.1

### get employee show info
GET {{endpoint}}/employee HTTP/1.1